# Generated by Django 5.2.12 on 2026-04-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_ai_prediction_calculation_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('maintenance', 'Maintenance')], default='online', max_length=50),
        ),
    ]
